# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GithubSearchApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GithubSearchApp

  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxViewController'
  pod 'Alamofire'
  pod 'Then'
  pod 'Kingfisher', '~> 5.0'
  pod 'SwiftyJSON'
  pod 'KeychainSwift'
  pod 'Gedatsu', configuration: %w(Debug)

  target 'GithubSearchAppTests' do
    inherit! :search_paths
    # Pods for testing
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxViewController'
  pod 'Alamofire'
  pod 'Then'
  pod 'Kingfisher', '~> 5.0'
  pod 'SwiftyJSON'
  pod 'KeychainSwift'
  pod 'Gedatsu', configuration: %w(Debug)
  end

end
